### ISSUE TITLE
psql cannot connect by default within Vagrant box

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-vagrant#337]
Identified during the docs sprint

When running psql as the vagrant user, psql errors because there's no role called `vagrant` in postgres.

**Comment by robredpath** [comment]
During the docs sprint, we've identified that the preferred workflow for analyst users is to connect to the pg database via an app (eg pgadmin) on the host system. The underlying logical model that we're currently working to is that the Vagrant box serves in lieu of hosted kingfisher - ie, it's just a server, not a dev env.

**Comment by odscjames** [comment]
Maybe a quick thing is just to make the appropriate psql command is documented in https://ocdskingfisher.readthedocs.io/en/latest/vagrant.html , maybe in a new section on "Working with the database". That can be used for #339 too.

**Comment by jpmckinney** [comment]
Above link is now https://kingfisher-vagrant.readthedocs.io/en/latest/

**Comment by jpmckinney** [comment]
And I see a section there now, so this issue is closed: https://kingfisher-vagrant.readthedocs.io/en/latest/#working-with-the-database
